apiVersion: v1
kind: LimitRange
metadata:
  namespace: mango
  name: mango-limits
  annotations:
    type: live
spec:
  limits:
    - default:
        cpu: 0.5
        memory: 128Mi
      defaultRequest:
        cpu: 0.25
        memory: 64Mi
      type: Container
