apiVersion: v1
kind: LimitRange
metadata:
  namespace: mango
  name: mango-limits
  annotations:
    type: live
spec:
  limits:
  - default:
      memory: 128Mi
    defaultRequest:
      memory: 64Mi
    type: Container