apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mango
  name: marketmaker-ftt-usdc
  labels:
    app: marketmaker
    cluster: devnet
    marketType: spot
    market: FTT_USDC
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marketmaker-ftt-usdc
  template:
    metadata:
      labels:
        app: marketmaker-ftt-usdc
    spec:
      containers:
        - name: marketmaker-ftt-usdc
          image: opinionatedgeek/mango-explorer-v3:latest
          imagePullPolicy: Always
          terminationMessagePolicy: FallbackToLogsOnError
          resources:
            limits:
              memory: 256Mi
            requests:
              memory: 64Mi
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          envFrom:
            - secretRef:
                name: marketmaker-delegate
            - configMapRef:
                name: cluster
            - configMapRef:
                name: notification-targets
          command:
            - marketmaker
            - --account-address
            - AEA9S5jjSkuAhjZrLuCw3aXGdYg6pqsMQAYS5KodkCD4
            - --name
            - "Spot FTT/USDC Marketmaker ($(NODE_NAME))"
            - --market
            - spot:FTT/USDC
            - --update-mode
            - POLL
            - --oracle-provider
            - ftx
            - --chain
            - ratios
            - --ratios-spread
            - "0.005"
            - --ratios-spread
            - "0.010"
            - --ratios-spread
            - "0.015"
            - --ratios-position-size
            - "0.0005"
            - --ratios-position-size
            - "0.001"
            - --ratios-position-size
            - "0.0015"
            - --chain
            - minimumcharge
            - --minimumcharge-ratio
            - "0.001"
            - --chain
            - biasquoteonposition
            - --biasquoteonposition-bias
            - "0.00005"
            - --chain
            - preventpostonlycrossingbook
            - --chain
            - roundtolotsize
            - --redeem-threshold
            - "1"
            - --existing-order-tolerance
            - "0.0001"
            - --minimumcharge-ratio
            - "0.0001"
            - --order-type
            - POST_ONLY
            - --blockhash-cache-duration
            - "30"
            - --log-level
            - CRITICAL
            - --log-suppress-timestamp
          # - --notify-errors
          # - $(ERRORS_TELEGRAM)
          livenessProbe:
            exec:
              command:
                - file-age-check
                - "180"
                - /var/tmp/mango_healthcheck_marketmaker_pulse
            initialDelaySeconds: 30
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - cat
                - /var/tmp/mango_healthcheck_marketmaker_pulse
            initialDelaySeconds: 30
            failureThreshold: 12
            periodSeconds: 5
      restartPolicy: Always
      initContainers:
        - name: ensure-openorders
          image: opinionatedgeek/mango-explorer-v3:latest
          imagePullPolicy: Always
          terminationMessagePolicy: FallbackToLogsOnError
          envFrom:
            - secretRef:
                name: marketmaker-delegate
            - configMapRef:
                name: cluster
          command:
            - ensure-open-orders
            - --account-address
            - AEA9S5jjSkuAhjZrLuCw3aXGdYg6pqsMQAYS5KodkCD4
            - --market
            - spot:FTT/USDC
            - --log-level
            - CRITICAL
