#! /usr/bin/env bash

export CLUSTER_NAME=mainnet
show-account-info --address AMzanZxMirPCgGcBoH9kw4Jzi9LFMomyUCXbpzDeL2T8 --filename root_bank0.json
show-account-info --address 8HjXYFntHMDNJKCJpHFufDaFYXfuAk6c6odfFnWc4xWy --filename root_bank1.json
show-account-info --address 8VwAANqu3t4KQKpMq7wrS6yg5GTHwJBFsrK4Tk2cFN3q --filename root_bank2.json
show-account-info --address FDpHjPQnUkmYVpAEVBpzb3sQgjZM7fanJoRb1VVtjF6u --filename root_bank3.json
show-account-info --address 7jH1uLmiB2zbHNe6juZZYjQCrvquakTwd3yMaQpeP8rR --filename root_bank4.json
show-account-info --address 4GYDmgvMpBx2n2iSmaS1xhZnwebR2gJ5V7UYUBA1PkJi --filename root_bank5.json
show-account-info --address AjMbjA1JsHh574Eo1RRV2XXtB8St139oBXKPXPo2HLdU --filename root_bank6.json
show-account-info --address 7TNHrBUDH3FL9uy9hxjmRcKNNaCBG9sYPuDJSJuj3LGs --filename root_bank7.json
show-account-info --address 6cMrtzhWNEEDkcSMx19orcred8h9HyRb31MtbCkKDdf6 --filename root_bank8.json

show-account-info --address 98pjRuQjK3qA6gXts96PqZT4Ze5QmnCmt3QYjhbUSPue --filename group.json
show-account-info --address EBDRoayCDDUvDgCimta45ajQeXbexv7aKqJubruqpyvu --filename cache.json

show-account-info --address 7eVBjqNwXzj8LFGECpkVH5suA22bagHvRXrtU9xf9cnh --filename openorders0.json
show-account-info --address HCQ4qTPAiWdr3tLdxBhxPUHXZQUdYqEddvfhgPqfKiDb --filename openorders1.json
show-account-info --address CVpWHhcWk6PHiRsziGk5oJz38ds9yc9vKXhWzW2EqDGH --filename openorders2.json

# From Nicky
# 'this one should be around 22.48%'
show-account-info --address 2BRWAijnbHbEwyPpSy4rvPNbukAupE2DVw2KCUGuLQg7 --filename account.json
