#! /usr/bin/env bash

export CLUSTER_NAME=mainnet
show-account-info --address 98pjRuQjK3qA6gXts96PqZT4Ze5QmnCmt3QYjhbUSPue --filename group.json
show-account-info --address EBDRoayCDDUvDgCimta45ajQeXbexv7aKqJubruqpyvu --filename cache.json
show-account-info --address AttyoZfCRtsTKbyPUzHP2bHWM8ZKA1n21e8kujQRPzFm --filename openorders3.json

# Random mainnet account that turned up in (incorrectly) liquidation calculations.
show-account-info --address T6xM61XvXQrhZjCZ9GnFbY4K7QNjUGhgRCRQYb2hM7P --filename account.json
