#!/usr/bin/env bash

CURRENT_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "${CURRENT_DIRECTORY}/.."

TAG=${1:-latest}

echo Building opinionatedgeek/mango-explorer:${TAG}
docker build . -t opinionatedgeek/mango-explorer:${TAG}
