#!/usr/bin/env bash

# This command takes a filename and a time (integer, in seconds) and exits successfully if the modification
# time of the file is less than the time given.
#
# This is useful for health checks that can be observed outside a container environment. For example, if
# an iteration of a market-maker writes to a 'health' file after every iteration, then a process (like a
# Kubernetes liveness check) can test that file to see if it has been updated within the last couple of
# minutes, and fail a 'liveness' check if it hasn't been.
#
FILENAME=${1:-/var/tmp/health}
let SECONDS_OLD=${2:-5}

let FILE_TIMESTAMP=$(date -r ${FILENAME} +'%s')
let CURRENT_TIME=$(date +'%s')
let FILE_AGE=${CURRENT_TIME}-${FILE_TIMESTAMP}

if [ ${FILE_AGE} -gt ${SECONDS_OLD} ]; then
    printf "File %s is too old.\n" ${FILENAME}
    exit 1
else
    printf "File %s is new enoug.\n" ${FILENAME}
fi