#!/usr/bin/env bash

CURRENT_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
START_COMMAND="start.sh jupyter lab --NotebookApp.iopub_data_rate_limit=9e9"
if [ "$1" == "notebook" ]; then
    START_COMMAND="start-notebook.sh"
fi

docker run -it --rm \
    -e GRANT_SUDO=yes --user root \
    -p 8888:8888 \
    --name mango-explorer \
    -v ${CURRENT_DIRECTORY}/..:/home/jovyan/work \
    opinionatedgeek/mango-explorer:latest \
    $START_COMMAND
