#!/usr/bin/env bash

CURRENT_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_DIRECTORY="${CURRENT_DIRECTORY}/.."

cd ${PROJECT_DIRECTORY}
grep -i -R --exclude-dir __pycache__ "${1}" bin/* mango/* *.ipynb tests/*
