name: Publish to Docker and Pypi on a new version tag

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  call-validation-workflow:
    uses: blockworks-foundation/mango-explorer/.github/workflows/test-and-lint.yaml@main
  call-docker-workflow:
    needs: call-validation-workflow
    uses: blockworks-foundation/mango-explorer/.github/workflows/publish-docker.yaml@main
    secrets:
      PROJECT_ID: ${{ secrets.GKE_PROJECT }}
      GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
      GKE_ZONE: ${{ secrets.GKE_ZONE }}
  call-pypi-workflow:
    needs: call-validation-workflow
    uses: blockworks-foundation/mango-explorer/.github/workflows/publish-pypi.yaml@main
    secrets:
      python_version: "3.9"
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
